export const themeMode = {
  lightMode: {
    '--mainTextColor': '#303133',
    '--heroTextColor': '#fff',
    '--commonTextColor': '#606266',
    '--reverseTextColor': '#fff',
    '--commonHoverBgc': '#F2F6FC',
    '--commonHoverHighLight': '#3ed5fe',
    '--commonSelectedBgc': '#3ed5fe',
    '--search-accent-color': '#3ed5fe',
    '--search-input-width': '140px',
    '--commonSelectedColor': '#ffffff',
    '--borderColor': '#909399',
    '--backgroundColor': '#fff',
    '--coverRegionColor': 'rgba(0, 0, 0, 0.5)',
    '--selectedCategoryCountColor': '#FFA500',
    '--defaultTagBgc': '#faecd8',
    '--textTipBgc': 'rgba(0, 0, 0, 0.4)',
    '--textTipColor': '#fff',
    '--navbarBgc': '#fff',
    '--navbarBoxShadow': 'rgba(0, 0, 0, 0.1)',
    '--navbarHeight': '3.6rem',
  },
};
